Don't source kamal secrets in Github actions

diff --git a/.kamal/secrets b/.kamal/secrets
--- a/.kamal/secrets
+++ b/.kamal/secrets
@@ -10,6 +10,12 @@
 # Use a GITHUB_TOKEN if private repositories are needed for the image
 # GITHUB_TOKEN=$(gh config get -h github.com oauth_token)
 
+# Bail out early in GitHub Actions
+# Otherwise, sourcing the below commands will fail
+if [ -n "${GITHUB_ACTIONS:-}" ]; then
+  return 0 2>/dev/null || exit 0
+fi
+
 # Grab the registry password
 KAMAL_REGISTRY_PASSWORD=$(aws ecr get-login-password --region us-east-1 --profile vanderoost)
 
